import { Layout } from "@/components/Layout";

export default function Disclaimer() {
  return (
    <Layout>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold text-foreground mb-8">Disclaimer</h1>

        <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">1. General Disclaimer</h2>
            <p>
              The Rural Healthcare System platform is designed as a decision-support tool to assist
              healthcare workers in rural communities. The information and assessments provided are
              generated by machine learning models and are intended to supplement — not replace —
              professional medical expertise.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">2. Not Medical Advice</h2>
            <p>
              The health risk assessments, disease predictions, and recommendations provided by this
              platform do not constitute medical advice, diagnosis, or treatment. All clinical decisions
              must be made by qualified healthcare professionals based on their own examination and
              judgment.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">3. Accuracy of Results</h2>
            <p>
              While we strive to provide accurate assessments, the predictions generated by the AI model
              are probabilistic in nature and may not always reflect the actual medical condition of a
              patient. Results should be interpreted in conjunction with clinical evaluation.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">4. No Guarantee</h2>
            <p>
              We do not guarantee the accuracy, completeness, or reliability of any assessment or
              recommendation provided through this platform. Use of the platform is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2">5. Emergency Situations</h2>
            <p>
              This platform is not intended for use in emergency medical situations. If a patient is
              experiencing a medical emergency, contact your local emergency services immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-2"></h2>
            <p>
            </p>
          </section>
          <p className="text-xs text-muted-foreground pt-4">Last updated: March 2026</p>
        </div>
      </div>
    </Layout>
  );
}
